#
#	Foundation Makefile
#
TOP = ../..

#
#	Foundation objects
# 
OBJS = \
NSObject.o \
NSAutoreleasePool.o \
NSArray.o \
NSArchiver.o \
NSAttributedString.o \
NSBundle.o \
NSCharacterSet.o \
NSCoder.o \
NSData.o \
NSDate.o \
NSDictionary.o \
NSDistributedLock.o \
NSException.o \
NSError.o \
NSFileHandle.o \
NSFileManager.o \
NSFormatter.o \
NSGeometry.o \
NSHashMap.o \
NSHost.o \
NSIndexPath.o \
NSIndexSet.o \
NSInvocation.o \
NSJSONSerialization.o \
NSLock.o \
NSLocale.o \
NSMethodSignature.o \
NSNotification.o \
NSNotificationCenter.o \
NSNotificationQueue.o \
NSNull.o \
NSNumber.o \
NSObjCRuntime.o \
NSPointerArray.o \
NSProcessInfo.o \
NSPropertyList.o \
NSRunLoop.o \
NSScanner.o \
NSSet.o \
NSStream.o \
NSString.o \
NSTask.o \
NSThread.o \
NSTimer.o \
NSTimeZone.o \
NSUndoManager.o \
NSURL.o \
NSUserDefaults.o \
NSUtilities.o \
NSXMLParser.o \
PropertyList.o \
Protocol.o \
Unicode.o \


LIBRARY = libFoundation

#
#	Include Makefiles 
# 
include $(TOP)/Build/library.make

