#
#	Makefile for Foundation Plugins
# 
#
TOP = ../..


# Subprojects built in a subdirectory
SUBPROJECTS = $(FX_PLUGINS)
# GZ.bproj \
# HTTPS.bproj \


#
#	Include Makefiles 
# 
include $(TOP)/Build/subproject.make


#
# General Rules
#
clean::
	rm -rf *.bundle
