#!/bin/sh
#

if [ -z "$1" ]; then
	echo usage: `basename $0` application [arguments...]
	exit 1
fi

app=$1;

# Remove leading slashes at the end of the application name
app=`echo $app | sed 's%/*$%%'`

case $app in
	/*)							# An absolute path.
		full_appname=$app;;
	*/*)						# A relative path
		full_appname=`(cd $app; pwd)`;;
	*)							# Search paths in PATH environment variable
		SPATH=.:$PATH
		IFS=:
		for dir in $SPATH; do
			if [ -d $dir/$app ]; then
				full_appname=`(cd $dir/$app; pwd)`
				break;
			fi
	done;;
esac

if [ -z "$full_appname" ]; then
	echo "Can't find the required application: $app!"
	exit 1
fi


appname=`echo $app | sed 's/\.[a-z]*$//'`

echo "Xapp path:" $full_appname/$appname

  if [ -f  ${HOME}/.mGSTEP/exports ]; then
	. ${HOME}/.mGSTEP/exports
  fi

  if [ -f  ../../ld-export ]; then
	. ../../ld-export
  fi


$full_appname/$appname $2 $3 $4 $5
