#
#	CoreFoundation Makefile
#
TOP = ..

#
#	CoreFoundation objects
# 
OBJS = \
CFBase.o \
CFRunLoop.o \
CFString.o \


LIBRARY = libCoreFoundation

#
#	Include Makefiles 
# 
include $(TOP)/Build/library.make

