#
#	AppKit Makefile
# 
TOP = ../..

#
#	AppKit Object Files
# 
OBJS = \
AXBase.o \
AXExterns.o \
AXPlatform.o \
AXServices.o \
CALayer.o \
NSActionCell.o \
NSAffineTransform.o \
NSApplication.o \
NSBezierPath.o \
NSBox.o \
NSBrowser.o \
NSButton.o \
NSCell.o \
NSClipView.o \
NSColor.o \
NSColorPanel.o \
NSColorWell.o \
NSComboBox.o \
NSControl.o \
NSCursor.o \
NSDocument.o \
NSEvent.o \
NSFont.o \
NSFontManager.o \
NSForm.o \
NSGraphicsContext.o \
NSImage.o \
NSImageRep.o \
NSImageView.o \
NSLayoutManager.o \
NSLevelIndicator.o \
NSMatrix.o \
NSMenu.o \
NSOutlineView.o \
NSPanel.o \
NSParagraphStyle.o \
NSPasteboard.o \
NSPopUpButton.o \
NSPrinter.o \
NSResponder.o \
NSSavePanel.o \
NSScreen.o \
NSScrollView.o \
NSScroller.o \
NSSearchField.o \
NSSecureTextField.o \
NSSegmentedControl.o \
NSSlider.o \
NSSound.o \
NSSpellChecker.o \
NSSplitView.o \
NSTabView.o \
NSTableView.o \
NSText.o \
NSTextField.o \
NSTextStorage.o \
NSTextView.o \
NSTypesetter.o \
NSView.o \
NSWindow.o \
NSWorkspace.o \
rtf.o \
tiff.o \
xdnd.o \


LIBRARY = libAppKit


#
#	Include Makefiles 
# 
include $(TOP)/Build/library.make

