#
#	Makefile for AppKit Plugins
# 
#
TOP = ../..


# Subprojects built in a subdirectory
SUBPROJECTS = $(IMG_PLUGINS) $(SND_PLUGINS)
# GIF.bproj \
# JPG.bproj \
# PNG.bproj \


#
#	Include Makefiles 
# 
include $(TOP)/Build/subproject.make


#
# General Rules
#
clean::
	rm -rf *.bundle *.audio
